import React, { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Image, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import theme from "../../constants/theme";
import { getCurrentCoords, isExpectedLocationError } from "../../lib/location";
import { filterDiscoveryItems, type DiscoveryMapItem } from "../../lib/discovery-map";
import type { GeoCoordinates } from "../../lib/event-map-types";
import type { MapFilterKey } from "./MapFilterChips";
import GoogleWebMap from "./GoogleWebMap";

type Props = { items: DiscoveryMapItem[]; loading: boolean; filters?: MapFilterKey[] };
export default function DiscoveryMapWeb({ items, loading, filters = ["near-me"] }: Props) {
  const router = useRouter(); const [location, setLocation] = useState<GeoCoordinates | null>(null); const [locationLoading, setLocationLoading] = useState(true); const [error, setError] = useState(""); const [selectedId, setSelectedId] = useState<string | null>(null); const [zoomLevel, setZoomLevel] = useState(13);
  const visibleItems = useMemo(() => filterDiscoveryItems(items, location, filters), [filters, items, location]);
  const selected = visibleItems.find((item) => item.id === selectedId) ?? null;
  const loadLocation = useCallback(async () => { setLocationLoading(true); setError(""); try { const coords = await getCurrentCoords(); if (!coords) { setError("Turn on location access to see nearby places."); return; } setLocation({ latitude: coords.latitude, longitude: coords.longitude }); } catch (value: unknown) { setError("Your current location could not be loaded."); if (!isExpectedLocationError(value)) console.error("Discovery map location failed:", value); } finally { setLocationLoading(false); } }, []);
  useEffect(() => { void loadLocation(); }, [loadLocation]);
  if (!location) return <View style={styles.state}>{locationLoading ? <><ActivityIndicator size="large" color={theme.COLORS.primary} /><Text style={styles.stateText}>Finding your current location…</Text></> : <><Ionicons name="location-outline" size={38} color={theme.COLORS.primary} /><Text style={styles.stateTitle}>Location needed</Text><Text style={styles.stateText}>{error}</Text><TouchableOpacity style={styles.retry} onPress={() => void loadLocation()}><Text style={styles.retryText}>Try again</Text></TouchableOpacity></>}</View>;
  const mapItems = visibleItems.map((item) => ({ ...item, latitude: item.latitude ?? location.latitude, longitude: item.longitude ?? location.longitude }));
  return <View style={styles.container}><GoogleWebMap center={selected ? { latitude: selected.latitude ?? location.latitude, longitude: selected.longitude ?? location.longitude } : location} markers={mapItems.map((item) => ({ id: item.id, title: item.title, latitude: item.latitude, longitude: item.longitude, imageUrl: item.imageUrl, kind: item.kind }))} selectedId={selectedId} onMarkerPress={(marker) => { setSelectedId(marker.id); setZoomLevel(15); }} height={560} zoomLevel={selected ? 15 : zoomLevel} showCenterMarker={!selected} /><View style={styles.mapControls}><TouchableOpacity style={styles.mapControlButton} onPress={() => setZoomLevel((value) => Math.min(value + 1, 20))}><Text style={styles.mapControlText}>+</Text></TouchableOpacity><TouchableOpacity style={styles.mapControlButton} onPress={() => setZoomLevel((value) => Math.max(value - 1, 3))}><Text style={styles.mapControlText}>−</Text></TouchableOpacity><TouchableOpacity style={styles.mapControlButton} onPress={() => { setSelectedId(null); setZoomLevel(13); }}><Ionicons name="locate" size={20} color={theme.COLORS.primary} /></TouchableOpacity></View>{loading ? <View style={styles.badge}><ActivityIndicator size="small" color={theme.COLORS.primary} /><Text style={styles.badgeText}>Updating {visibleItems[0]?.kind ?? "places"}</Text></View> : !visibleItems.length ? <View style={styles.emptyBadge}><Text style={styles.emptyText}>No locations found.</Text></View> : null}{selected ? <View style={styles.preview}>{selected.imageUrl ? <Image source={{ uri: selected.imageUrl }} style={styles.image} /> : null}<View style={styles.previewBody}><Text style={styles.previewTitle}>{selected.title}</Text><Text style={styles.previewLocation}>{selected.location}</Text><Text style={styles.previewMeta}>{selected.distanceKm != null ? `${selected.distanceKm.toFixed(1)} km away` : "Nearby"}</Text></View><TouchableOpacity style={styles.openButton} onPress={() => router.push(selected.detailRoute)}><Text style={styles.openButtonText}>View details</Text></TouchableOpacity></View> : null}</View>;
}
const styles = StyleSheet.create({ container: { height: 560, overflow: "hidden", backgroundColor: "#e2e8f0" }, state: { minHeight: 560, alignItems: "center", justifyContent: "center", padding: 36, backgroundColor: "#eff6ff" }, stateTitle: { marginTop: 13, color: theme.COLORS.textPrimary, fontSize: 17, fontWeight: "800" }, stateText: { marginTop: 7, color: theme.COLORS.textSecondary, fontSize: 13, textAlign: "center" }, retry: { marginTop: 18, borderRadius: 14, backgroundColor: theme.COLORS.primary, paddingHorizontal: 20, paddingVertical: 11 }, retryText: { color: "#fff", fontSize: 13, fontWeight: "800" }, mapControls: { position: "absolute", right: 14, bottom: 18, gap: 8 }, mapControlButton: { width: 44, height: 44, borderRadius: 22, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,255,255,0.97)", ...theme.SHADOWS.card }, mapControlText: { color: theme.COLORS.textPrimary, fontSize: 26, lineHeight: 28, fontWeight: "500" }, badge: { position: "absolute", top: 14, alignSelf: "center", flexDirection: "row", alignItems: "center", gap: 8, borderRadius: 999, paddingHorizontal: 14, paddingVertical: 9, backgroundColor: "rgba(255,255,255,0.97)", ...theme.SHADOWS.card }, badgeText: { color: theme.COLORS.textSecondary, fontSize: 12, fontWeight: "700" }, emptyBadge: { position: "absolute", top: 14, left: 20, right: 20, borderRadius: 16, padding: 12, backgroundColor: "rgba(255,255,255,0.97)", ...theme.SHADOWS.card }, emptyText: { color: theme.COLORS.textSecondary, fontSize: 13, fontWeight: "700", textAlign: "center" }, preview: { position: "absolute", left: 18, right: 18, bottom: 18, minHeight: 82, borderRadius: 20, padding: 11, flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: "rgba(255,255,255,0.98)", ...theme.SHADOWS.card }, image: { width: 60, height: 60, borderRadius: 16, backgroundColor: "#dbeafe" }, previewBody: { flex: 1, minWidth: 0 }, previewTitle: { color: theme.COLORS.textPrimary, fontSize: 16, fontWeight: "800" }, previewLocation: { marginTop: 3, color: theme.COLORS.textSecondary, fontSize: 12 }, previewMeta: { marginTop: 5, color: theme.COLORS.primary, fontSize: 12, fontWeight: "700" }, openButton: { minHeight: 44, borderRadius: 15, paddingHorizontal: 15, justifyContent: "center", backgroundColor: theme.COLORS.primary }, openButtonText: { color: "#fff", fontSize: 13, fontWeight: "800" }, });
