import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ActivityIndicator, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useRouter } from "expo-router";
import { Ionicons, MaterialIcons } from "@expo/vector-icons";
import theme from "../../constants/theme";
import { getCurrentCoords, isExpectedLocationError } from "../../lib/location";
import { filterDiscoveryItems, type DiscoveryMapItem } from "../../lib/discovery-map";
import type { GeoCoordinates } from "../../lib/event-map-types";
import type { MapFilterKey } from "./MapFilterChips";
import NativeMapboxMap from "./NativeMapboxMap";

type Props = { items: DiscoveryMapItem[]; loading: boolean; filters?: MapFilterKey[] };
export default function DiscoveryMap({ items, loading, filters = ["near-me"] }: Props) {
  const router = useRouter(); const [location, setLocation] = useState<GeoCoordinates | null>(null); const [locationLoading, setLocationLoading] = useState(true); const [error, setError] = useState(""); const [selectedId, setSelectedId] = useState<string | null>(null); const [zoomLevel, setZoomLevel] = useState(13);
  const visibleItems = useMemo(() => filterDiscoveryItems(items, location, filters), [filters, items, location]); const selected = visibleItems.find((item) => item.id === selectedId) ?? null;
  const loadLocation = useCallback(async () => { setLocationLoading(true); setError(""); try { const coords = await getCurrentCoords(); if (!coords) { setError("Turn on location access to see nearby places."); return; } setLocation({ latitude: coords.latitude, longitude: coords.longitude }); } catch (value: unknown) { setError("Your current location could not be loaded."); if (!isExpectedLocationError(value)) console.error("Discovery map location failed:", value); } finally { setLocationLoading(false); } }, []);
  useEffect(() => { void loadLocation(); }, [loadLocation]);
  if (!location) return <View style={styles.state}>{locationLoading ? <><ActivityIndicator size="large" color={theme.COLORS.primary} /><Text style={styles.stateText}>Finding your current location…</Text></> : <><Ionicons name="location-outline" size={38} color={theme.COLORS.primary} /><Text style={styles.stateTitle}>Location needed</Text><Text style={styles.stateText}>{error}</Text><TouchableOpacity style={styles.retry} onPress={() => void loadLocation()}><Text style={styles.retryText}>Try again</Text></TouchableOpacity></>}</View>;
  return <View style={styles.container}><NativeMapboxMap center={location} zoomLevel={zoomLevel} markers={visibleItems.map((item) => { const latitude = item.latitude ?? location.latitude; const longitude = item.longitude ?? location.longitude; return { id: item.id, kind: item.kind, coordinate: { latitude, longitude }, onPress: () => { setSelectedId(item.id); setZoomLevel(15); }, children: <View style={[styles.marker, selected?.id === item.id && styles.markerSelected]}><MaterialIcons name={item.kind === "event" ? "event" : item.kind === "spa" ? "spa" : item.kind === "hotel" ? "business" : "restaurant"} size={selected?.id === item.id ? 24 : 20} color="#ffffff" /></View> }; })} /><View style={styles.mapControls}><TouchableOpacity style={styles.mapControlButton} onPress={() => setZoomLevel((value) => Math.min(value + 1, 20))}><Text style={styles.mapControlText}>+</Text></TouchableOpacity><TouchableOpacity style={styles.mapControlButton} onPress={() => setZoomLevel((value) => Math.max(value - 1, 3))}><Text style={styles.mapControlText}>−</Text></TouchableOpacity><TouchableOpacity style={styles.mapControlButton} onPress={() => { setSelectedId(null); setZoomLevel(13); }}><Ionicons name="locate" size={20} color={theme.COLORS.primary} /></TouchableOpacity></View>{loading ? <View style={styles.badge}><ActivityIndicator size="small" color={theme.COLORS.primary} /><Text style={styles.badgeText}>Updating {visibleItems[0]?.kind ?? "places"}</Text></View> : !visibleItems.length ? <View style={styles.emptyBadge}><Text style={styles.emptyText}>No locations found.</Text></View> : null}{selected ? <View style={styles.preview}><Text style={styles.previewTitle}>{selected.title}</Text><Text style={styles.previewLocation}>{selected.location}</Text><TouchableOpacity style={styles.openButton} onPress={() => router.push(selected.detailRoute)}><Text style={styles.openButtonText}>View details</Text></TouchableOpacity></View> : null}</View>;
}
const styles = StyleSheet.create({ container: { height: 560, overflow: "hidden", backgroundColor: "#e2e8f0" }, state: { minHeight: 560, alignItems: "center", justifyContent: "center", padding: 36, backgroundColor: "#eff6ff" }, stateTitle: { marginTop: 13, color: theme.COLORS.textPrimary, fontSize: 17, fontWeight: "800" }, stateText: { marginTop: 7, color: theme.COLORS.textSecondary, fontSize: 13, textAlign: "center" }, retry: { marginTop: 18, borderRadius: 14, backgroundColor: theme.COLORS.primary, paddingHorizontal: 20, paddingVertical: 11 }, retryText: { color: "#fff", fontSize: 13, fontWeight: "800" }, marker: { width: 40, height: 40, borderRadius: 20, backgroundColor: "#16a34a", alignItems: "center", justifyContent: "center", elevation: 5, shadowColor: "#166534", shadowOpacity: 0.3, shadowRadius: 5 }, markerSelected: { borderWidth: 2, borderColor: "#ffffff", transform: [{ scale: 1.1 }] }, mapControls: { position: "absolute", right: 14, bottom: 18, gap: 8 }, mapControlButton: { width: 44, height: 44, borderRadius: 22, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,255,255,0.97)", elevation: 5 }, mapControlText: { color: theme.COLORS.textPrimary, fontSize: 26, lineHeight: 28 }, badge: { position: "absolute", top: 14, alignSelf: "center", flexDirection: "row", alignItems: "center", gap: 8, borderRadius: 999, paddingHorizontal: 14, paddingVertical: 9, backgroundColor: "rgba(255,255,255,0.97)", ...theme.SHADOWS.card }, badgeText: { color: theme.COLORS.textSecondary, fontSize: 12, fontWeight: "700" }, emptyBadge: { position: "absolute", top: 14, left: 20, right: 20, borderRadius: 16, padding: 12, backgroundColor: "rgba(255,255,255,0.97)", ...theme.SHADOWS.card }, emptyText: { color: theme.COLORS.textSecondary, fontSize: 13, fontWeight: "700", textAlign: "center" }, preview: { position: "absolute", left: 18, right: 18, bottom: 18, padding: 16, borderRadius: 20, backgroundColor: "#fff", elevation: 6 }, previewTitle: { color: theme.COLORS.textPrimary, fontSize: 16, fontWeight: "800" }, previewLocation: { marginTop: 4, color: theme.COLORS.textSecondary, fontSize: 12 }, openButton: { marginTop: 10, minHeight: 44, borderRadius: 15, paddingHorizontal: 15, alignItems: "center", justifyContent: "center", backgroundColor: theme.COLORS.primary }, openButtonText: { color: "#fff", fontSize: 13, fontWeight: "800" }, });
