import Constants from "expo-constants";
import React, { useMemo, useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { WebView } from "react-native-webview";
import type { GeoCoordinates } from "../../lib/event-map-types";

const MAPBOX_TOKEN = process.env.EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN || Constants.expoConfig?.extra?.mapboxAccessToken || Constants.manifest?.extra?.mapboxAccessToken || "";
const RESTAURANT_ICON = '<svg viewBox="0 0 512 512" width="22" height="22"><path fill="white" d="M96 16v192c0 35 29 64 64 64v224h48V272c35 0 64-29 64-64V16h-40v160h-24V16h-40v160h-24V16H96zm256 0c-53 0-96 43-96 96v96c0 35 29 64 64 64h8v224h48V272h8c35 0 64-29 64-64v-96c0-53-43-96-96-96z"/></svg>';
const SPA_ICON = '<svg viewBox="0 0 512 512" width="22" height="22"><path fill="white" d="M438 62C276 62 113 142 75 285c-24 91 19 165 91 165 93 0 127-111 157-205 25-79 55-130 115-183zM112 450c-1-88 36-159 111-222-64 75-88 139-89 222h-22z"/></svg>';
const HOTEL_ICON = '<svg viewBox="0 0 512 512" width="22" height="22"><path fill="white" d="M64 384V128h48v96h288v-64c0-18-14-32-32-32H160v-48h208c45 0 80 35 80 80v224h-48v-64H112v64H64zm48-112h288v48H112v-48z"/></svg>';
const EVENT_ICON = '<svg viewBox="0 0 512 512" width="22" height="22"><path fill="white" d="M128 48h32V16h48v32h96V16h48v32h32c35 0 64 29 64 64v320H64V112c0-35 29-64 64-64zm-16 128v208h288V176H112zm48 48h48v48h-48v-48zm80 0h48v48h-48v-48zm80 0h48v48h-48v-48z"/></svg>';
const HAPPY_HOUR_ICON = '<svg viewBox="0 0 512 512" width="22" height="22"><path fill="white" d="M64 96h384v64H64V96zm48 96h288l-32 256H144L112 192zm96 32v160h48V224h-48zm96 0v160h48V224h-48z"/></svg>';

export type NativeMapboxMarker = { id: string; coordinate: GeoCoordinates; children: React.ReactNode; onPress?: () => void; title?: string; kind?: "event" | "happy_hour" | "restaurant" | "spa" | "hotel" };
type Props = { center: GeoCoordinates; markers?: NativeMapboxMarker[]; zoomLevel?: number; height?: number; showUserLocation?: boolean; routeCoordinates?: GeoCoordinates[]; onPullToRefresh?: () => void };

export default function NativeMapboxMap({ center, markers = [], zoomLevel = 13, height, showUserLocation = true, routeCoordinates = [], onPullToRefresh }: Props) {
  const [mapError, setMapError] = useState("");
  const mapHtml = useMemo(() => {
    const markerData = markers.map((marker) => {
      const kind = marker.kind || "restaurant";
      const icon = kind === "spa" ? SPA_ICON : kind === "hotel" ? HOTEL_ICON : kind === "event" ? EVENT_ICON : kind === "happy_hour" ? HAPPY_HOUR_ICON : RESTAURANT_ICON;
      return { id: marker.id, title: marker.title || marker.id, latitude: marker.coordinate.latitude, longitude: marker.coordinate.longitude, kind, icon };
    });
    const route = routeCoordinates.map((point) => [point.longitude, point.latitude]);
    const json = JSON.stringify({ token: MAPBOX_TOKEN, center: [center.longitude, center.latitude], zoom: zoomLevel, markers: markerData, route, showUserLocation }).replace(/</g, "\\u003c");
    return `<!doctype html><html><head><meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no"/><link href="https://api.mapbox.com/mapbox-gl-js/v3.15.0/mapbox-gl.css" rel="stylesheet"/><style>html,body,#map{height:100%;margin:0}.marker{width:40px;height:40px;border-radius:50% 50% 50% 0;transform:rotate(-45deg);background:#2563eb;border:3px solid #fff;box-shadow:0 3px 10px #0f172a66;display:flex;align-items:center;justify-content:center}.marker.restaurant{background:#f97316}.marker.spa{background:#ec4899}.marker.hotel{background:#2563eb}.marker.event{background:#8b5cf6}.marker.happy_hour{background:#eab308}.marker svg{display:block;transform:rotate(45deg)}.user{width:18px;height:18px;border-radius:50%;background:#2563eb;border:4px solid #fff;box-shadow:0 2px 8px #0f172a66}</style></head><body><div id="map"></div><script src="https://api.mapbox.com/mapbox-gl-js/v3.15.0/mapbox-gl.js"></script><script>window.onerror=(message)=>window.ReactNativeWebView.postMessage(JSON.stringify({type:'error',message:String(message)}));let pullStartX=0;let pullStartY=0;document.addEventListener('touchstart',event=>{pullStartX=event.touches[0]?.clientX||0;pullStartY=event.touches[0]?.clientY||0},{passive:true});document.addEventListener('touchend',event=>{const endX=event.changedTouches[0]?.clientX||0;const endY=event.changedTouches[0]?.clientY||0;const deltaX=Math.abs(endX-pullStartX);const deltaY=endY-pullStartY;if(deltaY>70&&deltaY>deltaX*1.25){window.ReactNativeWebView.postMessage(JSON.stringify({type:'refresh'}))}},{passive:true});const config=${json};mapboxgl.accessToken=config.token;const map=new mapboxgl.Map({container:'map',style:'mapbox://styles/mapbox/streets-v12',center:config.center,zoom:config.zoom,attributionControl:true});map.on('error',()=>{});map.addControl(new mapboxgl.NavigationControl({showCompass:false}),'top-right');if(config.showUserLocation){new mapboxgl.Marker({element:Object.assign(document.createElement('div'),{className:'user'})}).setLngLat(config.center).addTo(map)}config.markers.forEach(item=>{const el=document.createElement('button');el.className='marker '+item.kind;el.title=item.title;el.innerHTML=item.icon;el.onclick=()=>window.ReactNativeWebView.postMessage(JSON.stringify({type:'marker',id:item.id}));new mapboxgl.Marker({element:el,anchor:'bottom'}).setLngLat([item.longitude,item.latitude]).addTo(map)});if(config.route.length>1){map.on('load',()=>{map.addSource('route',{type:'geojson',data:{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:config.route}}});map.addLayer({id:'route',type:'line',source:'route',paint:{'line-color':'#2563eb','line-width':5,'line-cap':'round','line-join':'round'}})})}</script></body></html>`;
  }, [center.latitude, center.longitude, markers, onPullToRefresh, routeCoordinates, showUserLocation, zoomLevel]);
  if (!MAPBOX_TOKEN || mapError) return <View style={[styles.container, styles.unavailable, height != null && { height }]}><Text style={styles.errorText}>{mapError || "Mapbox access token is not configured."}</Text></View>;
  return <View style={[styles.container, height != null && { height }]}><WebView originWhitelist={["*"]} source={{ html: mapHtml }} style={styles.map} javaScriptEnabled domStorageEnabled startInLoadingState onError={() => setMapError("Mapbox could not load the map.")} onHttpError={() => setMapError("Mapbox returned an error while loading the map.")} onMessage={(event) => { try { const message = JSON.parse(event.nativeEvent.data); if (message.type === "error") setMapError(message.message); if (message.type === "refresh") onPullToRefresh?.(); if (message.type === "marker") markers.find((marker) => marker.id === message.id)?.onPress?.(); } catch {} }} /></View>;
}

const styles = StyleSheet.create({ container: { width: "100%", height: "100%", overflow: "hidden", backgroundColor: "#dbeafe" }, map: { flex: 1 }, unavailable: { alignItems: "center", justifyContent: "center", padding: 16 }, errorText: { color: "#475569", fontSize: 12, fontWeight: "600", textAlign: "center" } });
